CREATE TABLE todos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR2(200) NOT NULL,
    done BOOLEAN DEFAULT FALSE NOT NULL
);

insert into todos (description, done) values ('Fare la spesa', true);
insert into todos (description) values ('Pagare le bollette');
insert into todos (description) values ('Pisciare il cane');
insert into todos (description) values ('Scendere la spazzatura');
