ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE USER devuser IDENTIFIED BY devpassword;

GRANT CREATE SESSION TO devuser;
GRANT CREATE TABLE TO devuser;
GRANT CREATE VIEW TO devuser;
GRANT CREATE SEQUENCE TO devuser;
GRANT CREATE PROCEDURE TO devuser;

ALTER USER devuser QUOTA UNLIMITED ON SYSTEM;
