<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\TodoApp.DataAccess\TodoApp.DataAccess.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>5851a6a9-c7e2-4da3-b3ef-60eb36ae9f38</UserSecretsId>
  </PropertyGroup>

</Project>
