services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: mssql-2025
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=Developer
    networks:
      - docker_network
    volumes:
      - mssql_data:/var/opt/mssql
    ports:
      - "127.0.0.1:1433:1433"

networks:
  docker_network:
    name: docker_network
    driver: bridge
    external: true

volumes:
  mssql_data:
    name: mssql-data
    driver: local
