<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\MaterieVoti.DataAccess\MaterieVoti.DataAccess.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>32c5c277-3cda-4642-bc76-83a473bb3160</UserSecretsId>
  </PropertyGroup>

</Project>
