<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\WebAppTodo.DataAccess\WebAppTodo.DataAccess.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>1df5927b-400c-4038-8885-ac482ab01da6</UserSecretsId>
  </PropertyGroup>

</Project>
