services:
  postgres:
    build: .
    image: postgres:18-ita
    container_name: postgres-server
    restart: unless-stopped
    shm_size: 128mb
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_INITDB_ARGS=--locale=it_IT.UTF-8 --auth=scram-sha-256
    networks:
      - postgres_network
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "127.0.0.1:5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - SERVER_MODE=false
    networks:
      - docker_network
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "127.0.0.1:8082:80"

#  adminer:
#    image: adminer:latest
#    container_name: adminer
#    restart: unless-stopped
#    depends_on:
#      - postgres
#    networks:
#      - docker_network
#    ports:
#      - "127.0.0.1:8081:8080"

networks:
  docker_network:
    name: docker_network

volumes:
  postgres_data:
    name: postgresql-data
  pgadmin_data:
    name: pgadmin-data
