<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\JsonPlaceholder.DataAccess\JsonPlaceholder.DataAccess.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="dataset\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
